Add cycling sequence workchain
epfl-theos/aiida-aurora pull request #19
Opened 2023-06-12 12:51 UTC by ramirezfranciscof

2023-07-19 14:05 UTC, edan-bainglass commented
Workflow looks good! Per our discussion, we'll settle on a standard for techniques/protocols following user inquiry, then address monitoring after we upgrade to aiida-core 2.x.

2023-07-19 14:08 UTC, edan-bainglass reviewed
Workflow looks good! Per our discussion, we'll settle on a standard for techniques/protocols following user inquiry, then address monitoring after we upgrade to aiida-core 2.x.

2023-07-19 14:08 UTC, edan-bainglass commented on aiida_aurora/workflows/cycling_sequence.py
> +        # yapf: disable
Why disable yapf?

2023-07-19 14:08 UTC, edan-bainglass commented on aiida_aurora/workflows/cycling_sequence.py
> +            "techniques",
Need to settle on a standard for techniques/protocols through user inquiry. Checking...

2023-07-20 14:19 UTC, edan-bainglass commented on aiida_aurora/workflows/cycling_sequence.py
> +            "techniques",
Received user feedback. This should be `protocols`, which is a collection of individual protocols, each being a sequence of `techniques`.

2023-08-23 09:20 UTC, edan-bainglass approved these changes
LGTM! However, some of your changes will no longer be necessary due to updates on my end:

- `Rename cycling sequence test` - I updated the CI in #27 to only run `pytest` on the _tests_ directory
- `Fix errors on CI due to pydantic` - I pinned pydantic's version in #26

Maybe check/approve #26 and #27 and rebase this on top?

2023-08-28 06:11 UTC, edan-bainglass requested changes
There is still a confusion between protocol and technique concepts. It seems to me that both singular and plural cases of protocol rely on `ElectroChemSequence` as a schema. But this surely is incorrect, right? The plural is of course a set of the singular, but the singular is a set of techniques, so different. Need to discuss/clarify.

2023-08-28 06:11 UTC, edan-bainglass commented on aiida_aurora/workflows/cycling_sequence.py
> +            'technique': self.inputs.protocols[current_keyname],
`'technique'` should be `'protocol'`. As discussed, changes need to be made in `cycler.py` to uniform the language. As a reminder, `protocols` are a set of ``protocol` instances, e.g. "formation", "cycling", each made up of a set of `technique` instances, e.g. "OCV", "CC", "LOOP", etc.

2023-08-28 06:11 UTC, edan-bainglass commented on examples/cycling_sequence/test_cycling_sequence.py
> +workflow_builder.techniques = {
`workflow_builder.protocols`

2023-08-28 10:12 UTC, ramirezfranciscof reviewed
Changes to apply

2023-08-28 10:12 UTC, ramirezfranciscof commented on aiida_aurora/workflows/cycling_sequence.py
> +            'technique': self.inputs.protocols[current_keyname],
```suggestion
            'protocol': self.inputs.protocols[current_keyname],
```

2023-08-28 10:12 UTC, ramirezfranciscof commented on aiida_aurora/workflows/cycling_sequence.py
> +        """Takes the inputs and wraps them together."""
```suggestion
        """Take the inputs and wrap them together."""
```

2023-08-28 10:12 UTC, ramirezfranciscof commented on examples/cycling_sequence/test_cycling_sequence.py
> +    """Generated the inputs."""
```suggestion
    """Generate the inputs."""
```

2023-08-28 10:12 UTC, ramirezfranciscof commented on examples/cycling_sequence/test_cycling_sequence.py
> +workflow_builder.techniques = {
```suggestion
workflow_builder.protocols = {
```

2023-08-29 14:42 UTC, edan-bainglass commented
I still don't understand. You did all of this in response to my request for changes? It was not already there?

2023-08-30 04:51 UTC, edan-bainglass commented
Review recap (detailed and accurate 🤞)
======================

1. Approved as is (too hasty - found this out once I started modifying the workflow for monitoring)
2. Noticed you addressing items that have been taken care of in the AiiDA 2.x upgrade and were no longer necessary (fixed 👍)
3. Noticed that `technique` was not changed to `protocol` as discussed (fixed 👍)
4. Found `technique` references in `cycler.py` (yet to be fixed)

This brings us to the present. Now, regarding my comment about too many changes in this latest round, that's my bad. I was looking at ALL PR commits, rather than just the commit details of `FIX: Corrections from PR review`. That looks good to me, but it still does not address review 4. At this point, do you mind if I address the rest? I need to finalize this thing by end of week, and really, I only have today (packing and moving to new office Th/F).

Let me know 🙏

2023-08-30 09:34 UTC, ramirezfranciscof commented
> The commit looks good to me, but it still does not address review 4. At this point, do you mind if I address the rest? I need to finalize this thing by end of week, and really, I only have today (packing and moving to new office Th/F).

Sure, no problem you can go ahead. But I think I applied all the changes from the previous reviews (except maybe the yapf ignore statements that I think just make the specs declaration harder to read). Which one is review 4, [this one](https://github.com/epfl-theos/aiida-aurora/pull/19#pullrequestreview-1600521958)? I answered the questions but I'm not sure what else is there to address...

2023-08-30 11:00 UTC, edan-bainglass commented
In my previous message, 1-3 are done! 4 was not yet addressed, i.e. you changed the reference to the calculation's `technique` in the workflow, but not in the actual calcjob.

In any case, I'll rebase and address the rest, including my changes. You can review all that in a bit.

2023-08-30 11:01 UTC, edan-bainglass commented
By the way, how would I go about proceeding? Do I push my changes to your fork, so that it is reflected in the PR? Or is there another way?

2023-08-30 18:22 UTC, merged